services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app-node:
    build: ./apps/node-service
    ports:
      # Host 3000 = app Node (costuma ser o que as pessoas testam primeiro). Dentro do container continua :3001.
      - "3000:3001"
    environment:
      REDIS_URL: redis://redis:6379
      CACHE_TTL_SECONDS: "10"
      PORT: "3001"
    depends_on:
      redis:
        condition: service_healthy

  app-python:
    build: ./apps/python-service
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379
      CACHE_TTL_SECONDS: "60"
      PORT: "8000"
    depends_on:
      redis:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    depends_on:
      - app-node
      - app-python

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: dark
      GF_SERVER_ROOT_URL: http://localhost:3002
    volumes:
      - ./infra/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./infra/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
